INCLUDE EMU8086.INC
ORG 100H

.DATA
VAR1 DW ?
VAR2 DW ?
OPTION DW ?
ANS DW ?

.CODE
MAIN PROC
    PRINT "WELCOME TO CALCULATOR!!"
    START:
    PRINTN
    PRINT "CHOOSE YOUR PREFFERED OPTION:"
    PRINTN
    PRINT "1. ADDITION 2. SUBTRACTION 3. MULTIPLICATION 4. DIVISION 5. EXPONENTIAL 6. FACTORIAL 7.PERCENTAGE 8. EXIT"
    PRINTN
    CALL SCAN_NUM
    CMP CX,1
    JE ADDITION
    CMP CX,2
    JE SUBTRACTION
    CMP CX,3
    JE MULTIPLICATION
    CMP CX,4
    JE DIVISION
    CMP CX,5
    JE POWER
    CMP CX,6 
    JE FACTORIAL
    CMP CX,7
    JE PERCENTAGE
    CMP CX,8
    JE END
    
        
ADDITION:
    PRINTN 
    PRINT "ENTER FIRST VALUE : "
    CALL SCAN_NUM
    MOV VAR1,CX
    PRINTN 
    PRINT "ENTER SECOND VALUE : "
    CALL SCAN_NUM
    MOV VAR2,CX
    
    ADD CX,VAR1
    MOV AX,CX
    PRINTN
    PRINT "AFTER ADDITION, THE ANSWER IS = "
    CALL PRINT_NUM
    MOV ANS,AX
    JMP END

SUBTRACTION:
    PRINTN 
    PRINT "ENTER FIRST VALUE : "
    CALL SCAN_NUM
    MOV VAR1,CX
    PRINTN 
    PRINT "ENTER SECOND VALUE : "
    CALL SCAN_NUM
    MOV VAR2,CX
    
    SUB VAR1,CX
    MOV AX,VAR1
    PRINTN
    PRINT "AFTER SUBTRACTION, THE ANSWER IS = "
    CALL PRINT_NUM
    MOV ANS,AX
    JMP END
    
MULTIPLICATION:
    PRINTN 
    PRINT "ENTER FIRST VALUE : "
    CALL SCAN_NUM
    MOV VAR1,CX
    PRINTN 
    PRINT "ENTER SECOND VALUE : "
    CALL SCAN_NUM
    MOV VAR2,CX
    MOV AX,VAR1
    MUL CX
    PRINTN
    PRINT "AFTER MULTIPLICATION, THE ANSWER IS = "
    CALL PRINT_NUM
    MOV ANS,AX
    JMP END        
    
DIVISION:
    PRINTN 
    PRINT "ENTER FIRST VALUE : "
    CALL SCAN_NUM
    MOV VAR1,CX
    PRINTN 
    PRINT "ENTER SECOND VALUE : "
    CALL SCAN_NUM
    MOV VAR2,CX
    CMP VAR2,0
    JE INFINITE
    MOV AX,VAR1
    DIV CX
    PRINTN
    PRINT "AFTER DIVISION, THE ANSWER IS = "
    CALL PRINT_NUM
    MOV ANS,AX
    JMP END

POWER:
    PRINTN 
    PRINT "ENTER VALUE : "
    CALL SCAN_NUM
    MOV VAR1,CX
    PRINTN 
    PRINT "ENTER EXPONENTIAL : "
    CALL SCAN_NUM
    MOV VAR2,CX
    SUB CX,1
    MOV AX,VAR1
    L1:
        MUL VAR1
        LOOP L1        
    PRINTN
    PRINT "AFTER EXPONENTIAL, THE ANSWER IS = "
    CALL PRINT_NUM
    JMP END
    
FACTORIAL:
    PRINTN 
    PRINT "ENTER VALUE : "
    CALL SCAN_NUM
    MOV VAR1,CX
    MOV AX,1
    L2:
        MUL CX
        LOOP L2        
    PRINTN
    PRINT "AFTER FACTORIAL, THE ANSWER IS = "
    CALL PRINT_NUM
    JMP END

PERCENTAGE:
    PRINTN 
    PRINT "ENTER VALUE : "
    CALL SCAN_NUM
    MOV VAR1,CX
    PRINTN 
    PRINT "ENTER TOTAL : "
    CALL SCAN_NUM
    MOV VAR2,CX
    MOV AX,VAR1
    MOV BX,100
    MUL BX
    DIV CX
    PRINTN
    PRINT "AFTER PERCENTAGE, THE ANSWER IS = "
    CALL PRINT_NUM
    PRINT ' %'
    MOV ANS,AX
    JMP END
INFINITE:
    PRINTN
    PRINT "AFTER DIVISION, THE VALUE IS UNDEFINED"
    JMP END
END:
MAIN ENDP
DEFINE_SCAN_NUM
DEFINE_PRINT_NUM
DEFINE_PRINT_NUM_UNS
